### ISSUE TITLE
Assertion in analyze_position fails

### ISSUE THREAD

**Issue by buffet** [clausecker/dobutsu#2]
Ran `show lines` in a position one move away from getting my lion captured, got

```
18. show lines
dobutsu: ai.c:91: analyze_position: Assertion `nmove == 0 || total > 0'` failed.
```

Sadly in an attempt to get a simple repro everything scrolled too far up to retrieve it, and I couldn't manage to reproduce this.

**Comment by clausecker** [comment]
Greetings!  Do you recall if you set the player strength to something weird with the `strength` command?

**Comment by buffet** [comment]
Yup, `strength 1000`.

**Comment by clausecker** [comment]
Yeah that's an overflow.  Values above 700 are not supported and should have been clamped.  I'll check how that happened and adjust the clamping code if needed.

**Comment by clausecker** [comment]
If you speak a language other than the ones this software has already been translated to (German, Latvian), may I interest you in assisting in the translation to a new language?

**Comment by buffet** [comment]
I do not, sadly.
